### ISSUE TITLE
gpstest.py broken pipe error

### ISSUE THREAD

**Issue by dima72** [sixfab/Sixfab_RPi_3G-4G-LTE_Base_Shield#4]
https://github.com/sixfab/Sixfab_RPi_3G-4G-LTE_Base_Shield/blob/master/tutorials/GPS/gpstest.py

```
Connecting port
Receiving GPS data
Traceback (most recent call last):
  File "gpstest.py", line 48, in <module>
    ser = serial.Serial(port, baudrate = 115200, timeout = 0.5)
  File "/usr/lib/python2.7/dist-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
IOError: [Errno 32] Broken pipe
```

**Comment by dima72** [comment]
reinstall pyserial2.7 worked for me to solve 'Broken Pipe' problem

sudo pip install --force-reinstall pyserial==2.7
